update onlineboutique with latest version

diff --git a/namespaces/onlineboutique/loadgenerator.yaml b/namespaces/onlineboutique/loadgenerator.yaml
--- a/namespaces/onlineboutique/loadgenerator.yaml
+++ b/namespaces/onlineboutique/loadgenerator.yaml
@@ -3,7 +3,7 @@ kind: ServiceAccount
 metadata:
   name: loadgenerator
   annotations:
-    iam.gke.io/gcp-service-account: boutique-gsa@mabenoit-meetup.iam.gserviceaccount.com
+    iam.gke.io/gcp-service-account: onlineboutique-gsa@mabenoit-startup-demo.iam.gserviceaccount.com
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -24,9 +24,25 @@ spec:
       serviceAccountName: loadgenerator
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
       containers:
       - name: main
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.2.4
         env:
         - name: FRONTEND_ADDR
           value: "frontend:80"
